# Generated by Django 4.1.6 on 2023-03-10 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sayt', '0002_alter_new_short_desc'),
        ('sayt', '0002_new_desc_new_img'),
    ]

    operations = [
    ]
