# Generated by Django 4.1.6 on 2023-03-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayt', '0003_merge_0002_alter_new_short_desc_0002_new_desc_new_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='img',
            field=models.ImageField(upload_to='images'),
        ),
    ]
