# Generated by Django 4.1.6 on 2023-03-15 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayt', '0004_alter_new_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='views',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
