# Generated by Django 4.1.6 on 2023-03-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayt', '0005_new_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
