# Generated by Django 4.1.6 on 2023-03-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayt', '0006_alter_new_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('phone', models.CharField(max_length=18)),
                ('msg', models.TextField()),
            ],
        ),
    ]
