# Generated by Django 4.1.6 on 2023-04-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regis', '0002_user_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=512)),
                ('phone', models.CharField(max_length=20)),
                ('is_expired', models.BooleanField(default=False)),
                ('step', models.CharField(max_length=50)),
                ('tries', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
